### ISSUE TITLE
Gamma correction done twice if source map is set

### ISSUE THREAD

**Issue by kunaakos** [beyondscreen/node-rpi-ws281x-native#30] opened 2015-07-08 12:11 UTC
I think [this line](https://github.com/raspberry-node/node-rpi-ws281x-native/blob/master/lib/ws281x-native.js#L100) should be:
```JavaScript
data[i] = _tmpData[indexMapping[i]];
```
Gamma correction is done in render()

**Comment by usefulthink** [comment] 2015-07-09 10:15
duplicate of #28

**Comment by usefulthink** [comment] 2015-07-09 10:21
the problem is, the gamma-correction is applied to the data-array that is most likely reused for rendering the next frame. Thus, if you don't write the whole data-array on every frame the initially set colors will fade to black over time (because the correction is applied over and over again).

**Comment by tsuckow** [comment] 2015-08-09 20:24
I don't think render should be doing any of this stuff or at the very least there should be a "renderRaw" method that doesn't do any of these transformations.

If you do wish to do this, you should have your own buffer that is created at init time and used as the scratch space.

**Comment by usefulthink** [comment] 2015-08-10 09:39
I agree. Wasn't the best Idea to have this in the core. Will be removed in the next version.

**Comment by usefulthink** [comment] 2015-11-27 01:16
With the rewrite of the native part for version 0.6 this is now working properly, as the data passed by the application is not modified anymore.

**Closed by usefulthink** 2015-11-27 01:16 UTC
